CREATE TABLE AUTHOR
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE GENRE
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOK
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

CREATE TABLE BOOK_AUTHOR
(
    BOOK_ID   BIGINT,
    AUTHOR_ID   BIGINT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
    CONSTRAINT CK_BOOK_AUTHOR PRIMARY KEY (BOOK_ID, AUTHOR_ID)
);

CREATE TABLE BOOK_GENRE
(
    BOOK_ID   BIGINT,
    GENRE_ID   BIGINT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
    CONSTRAINT CK_BOOK_GENRE PRIMARY KEY (BOOK_ID, GENRE_ID)
);